/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package info5100.university.example.Ui.StudentRole;

/**
 *
 * @author Srija
 */
public class GraduationAuditJPanel extends javax.swing.JPanel {

    /**
     * Creates new form GraduationAuditJPanel
     */
    public GraduationAuditJPanel() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblStudentId = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        lblStudentName = new javax.swing.JLabel();
        btnBack = new javax.swing.JButton();
        btnRunAudit = new javax.swing.JButton();
        lblOverallGpaValue = new javax.swing.JLabel();
        lblTermGpaValue = new javax.swing.JLabel();
        lblProgram = new javax.swing.JLabel();
        lblOverallGpa = new javax.swing.JLabel();
        pnlProgress1 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        lblCreditsEarned1 = new javax.swing.JLabel();
        lblCreditsRemaining1 = new javax.swing.JLabel();
        prgCredits1 = new javax.swing.JProgressBar();
        lblCreditsRequired1 = new javax.swing.JLabel();
        scrRequirements = new javax.swing.JScrollPane();
        tblRequirements1 = new javax.swing.JTable();
        scrInProgress = new javax.swing.JScrollPane();
        tblInProgress1 = new javax.swing.JTable();
        jLabel5 = new javax.swing.JLabel();
        lblReady = new javax.swing.JLabel();

        setBackground(new java.awt.Color(0, 204, 204));

        lblStudentId.setText("Student ID :     ");

        jLabel1.setFont(new java.awt.Font("Helvetica Neue", 0, 20)); // NOI18N
        jLabel1.setText("Graduate Audit");

        lblStudentName.setText("Name:    ");

        btnBack.setText("<<< Back");
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });

        btnRunAudit.setText("Run Audit");
        btnRunAudit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRunAuditActionPerformed(evt);
            }
        });

        lblOverallGpaValue.setText("                   ");

        lblTermGpaValue.setText("                ");

        lblProgram.setText("Program :");

        lblOverallGpa.setText("Overall GPA :");

        pnlProgress1.setBackground(new java.awt.Color(0, 204, 204));

        jLabel4.setFont(new java.awt.Font("Helvetica Neue", 0, 16)); // NOI18N
        jLabel4.setText("Progress");

        lblCreditsEarned1.setText("Credits Earned:   ");

        lblCreditsRemaining1.setText("Credits Remaining:       ");

        prgCredits1.setMaximum(32);

        lblCreditsRequired1.setText("Credits Required:       ");

        javax.swing.GroupLayout pnlProgress1Layout = new javax.swing.GroupLayout(pnlProgress1);
        pnlProgress1.setLayout(pnlProgress1Layout);
        pnlProgress1Layout.setHorizontalGroup(
            pnlProgress1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlProgress1Layout.createSequentialGroup()
                .addGroup(pnlProgress1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlProgress1Layout.createSequentialGroup()
                        .addGap(366, 366, 366)
                        .addComponent(jLabel4))
                    .addGroup(pnlProgress1Layout.createSequentialGroup()
                        .addGap(15, 15, 15)
                        .addGroup(pnlProgress1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblCreditsEarned1)
                            .addComponent(lblCreditsRemaining1)
                            .addComponent(lblCreditsRequired1)
                            .addComponent(prgCredits1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(386, Short.MAX_VALUE))
        );
        pnlProgress1Layout.setVerticalGroup(
            pnlProgress1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlProgress1Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(prgCredits1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(lblCreditsEarned1)
                .addGap(18, 18, 18)
                .addComponent(lblCreditsRequired1)
                .addGap(18, 18, 18)
                .addComponent(lblCreditsRemaining1)
                .addContainerGap(46, Short.MAX_VALUE))
        );

        tblRequirements1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Requirement", "Needed", "Earned", "Remaining", "Status"
            }
        ));
        tblRequirements1.setColumnSelectionAllowed(true);
        tblRequirements1.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        scrRequirements.setViewportView(tblRequirements1);
        tblRequirements1.getColumnModel().getSelectionModel().setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);

        tblInProgress1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Term", "Course ID", "Course Name", "Credits", "Status"
            }
        ));
        scrInProgress.setViewportView(tblInProgress1);
        tblInProgress1.getColumnModel().getSelectionModel().setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);

        jLabel5.setFont(new java.awt.Font("Helvetica Neue", 0, 16)); // NOI18N
        jLabel5.setText("Requirements");

        lblReady.setText("Not Evaluated");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 18, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                    .addComponent(lblStudentId)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(lblTermGpaValue, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                    .addComponent(lblStudentName)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(lblOverallGpaValue, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                            .addComponent(lblOverallGpa)
                            .addComponent(lblProgram))
                        .addContainerGap(661, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(pnlProgress1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(23, Short.MAX_VALUE))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel5)
                .addGap(386, 386, 386))
            .addGroup(layout.createSequentialGroup()
                .addGap(114, 114, 114)
                .addComponent(btnRunAudit)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lblReady)
                .addGap(232, 232, 232))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(scrInProgress, javax.swing.GroupLayout.PREFERRED_SIZE, 813, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(scrRequirements, javax.swing.GroupLayout.PREFERRED_SIZE, 807, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(btnBack)
                    .addGap(247, 247, 247)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(349, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnRunAudit)
                    .addComponent(lblReady))
                .addGap(34, 34, 34)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblOverallGpaValue)
                    .addComponent(lblStudentName))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblTermGpaValue)
                    .addComponent(lblStudentId))
                .addGap(12, 12, 12)
                .addComponent(lblProgram)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblOverallGpa)
                .addGap(4, 4, 4)
                .addComponent(jLabel5)
                .addGap(18, 18, 18)
                .addComponent(scrRequirements, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(9, 9, 9)
                .addComponent(pnlProgress1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(scrInProgress, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(90, Short.MAX_VALUE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addContainerGap()
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jLabel1)
                        .addComponent(btnBack))
                    .addContainerGap(812, Short.MAX_VALUE)))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed

    }//GEN-LAST:event_btnBackActionPerformed

    private void btnRunAuditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRunAuditActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnRunAuditActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnRunAudit;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel lblCreditsEarned1;
    private javax.swing.JLabel lblCreditsRemaining1;
    private javax.swing.JLabel lblCreditsRequired1;
    private javax.swing.JLabel lblOverallGpa;
    private javax.swing.JLabel lblOverallGpaValue;
    private javax.swing.JLabel lblProgram;
    private javax.swing.JLabel lblReady;
    private javax.swing.JLabel lblStudentId;
    private javax.swing.JLabel lblStudentName;
    private javax.swing.JLabel lblTermGpaValue;
    private javax.swing.JPanel pnlProgress1;
    private javax.swing.JProgressBar prgCredits1;
    private javax.swing.JScrollPane scrInProgress;
    private javax.swing.JScrollPane scrRequirements;
    private javax.swing.JTable tblInProgress1;
    private javax.swing.JTable tblRequirements1;
    // End of variables declaration//GEN-END:variables
}
